Definition ::= Directive+

Directive ::= DirectiveItem

DirectiveItem ::= GateDef | LinkDef

GateDef ::= "DEFINE" GateIdentifier "AS" GateTy

GateTy ::= "not"
	| "and"
	| "or"
	| "xor"
	| "nand"
	| "nor"

LinkDef ::= "LINK" GateIdentifier "->" InputIdentifier "OF" GateIdentifier 

GateIdentifier ::= [a-z] [a-z_]+

InputIdentifier ::= [a-z]
